#
# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
# this file works for NetBSD
#
# provided by Marc Baudoin <babafou@babafou.eu.org>
#

CC= cc -O
#CC= cc -g -DDEBUG
#CC= gcc -g -Wall
#
# standard line for normal searching
CFLAGS= -DM10_CONS -DUNIX -DTIMES -DHZ=60 -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit -DPROGRESS -DFASTA_HOST='"your.host.here/fasta/cgi"' -DUSE_MMAP

# special options for SUPERFAMLIES
#CFLAGS= -DM10_CONS -DUNIX -DTIMES -DHZ=60 -DSFCHAR="'|'" -c -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit -DPROGRESS -DSUPERFAMNUM -DUSE_MMAP

LIB_M= -lm
HFLAGS= -o
NFLAGS= -o

# for NetBSD
THR_SUBS = pthr_subs2
THR_LIBS = -L/usr/pkg/pthreads/lib -lpthread
THR_CC = -I/usr/pkg/pthreads/include

XDIR = /seqprg/slib/bin

DROPNFA_O = drop_nfa.o
DROPGSW_O = dropgsw.o
DROPRSS_O = dropnsw.o

include Makefile34m.common
