# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
# this file works for DEC Alphas
#
# this file supports mmap()'ed databases in BLAST2 format use -DUSE_MMAP
# for mmap()ed BLAST2 format.

# the -DDEBUG option provides additional debugging information, particularly
# with -D on the command line.

# use -DBIG_LIB64 to generate 64-bit offsets in map_db .xin files

# changed to gcc-3.3 for MacOSX Tiger because of problems with Altivec
#

# in my hands, gcc-4.0 is about 40% slower than gcc-3.3 on the Altivec code
#CC= gcc-4.0 -g -falign-loops=32 -O3 -mcpu=7450 -maltivec -mpim-altivec -DSW_ALTIVEC

CC= gcc-3.3 -g -falign-loops=32 -O3 -mcpu=7450 -faltivec -DSW_ALTIVEC
#CC= gcc-3.3 -g -DDEBUG -mcpu=7450 -faltivec -DSW_ALTIVEC
#CC= cc -g -Wall -pedantic -faltivec -DSW_ALTIVEC
#
# standard line for normal searching
CFLAGS= -DSHOWSIM -DM10_CONS -DUNIX -DTIMES -DHZ=100 -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit -DPROGRESS -DFASTA_HOST='"xs00.achs.virginia.edu/fasta_www/cgi"' -DUSE_MMAP -DUSE_FSEEKO -DHAS_INTTYPES -DSAMP_STATS -DPGM_DOC

#CFLAGS= -DSHOWSIM -DM10_CONS -DUNIX -DTIMES -DHZ=60 -DMAX_WORKERS=2 -DTHR_EXIT=pthread_exit -DPROGRESS -DFASTA_HOST='"xs00.achs.virginia.edu/fasta_www/cgi"' -DUSE_MMAP -DUSE_FSEEKO -DHAS_INTTYPES -DSAMP_STATS -DPGM_DOC -DSUPERFAMNUM -DSFCHAR="'|'"

# add for MySQL support
# -I/usr/local/mysql/include -DMYSQL_DB

HFLAGS= -o
NFLAGS= -o

#for DEC Unix V4.0 
THR_SUBS = pthr_subs2
THR_LIBS =
THR_CC =

#for Sun
#THR_SUBS = uthr_subs2
#THR_LIBS = -lthread
#THR_CC =
#
# for SGI with current pthreads
#THR_SUBS = pthr_subs2
#THR_LIBS = -lpthreads
#THR_CC = 
#
# for IBM with current pthreads
#CC= xlc_r -v -g
#THR_SUBS = ibm_pthr_subs2
#THR_LIBS = -lpthreads
#THR_CC =


#XDIR = ${HOME}/bin
#XDIR = /home/slib/bin/MACOSX/
#XDIR = /Users/seqprg/bin
XDIR = /seqprg/bin
#XDIR = ./ppc

DROPNFA_O = drop_nfa.o
DROPTFA_O = drop_tfa.o
DROPGSW_O = dropgsw.o smith_waterman_altivec.o
DROPRSS_O = dropgsw.o smith_waterman_altivec.o
#DROPGSW_O = dropgsw.o
#DROPRSS_O = dropgsw.o

# provide mysql function
#include Makefile34m.common_sql

# no mysql
include Makefile34m.common
