#
# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
#
#
# Dec 8, 2005 - with gcc4.0.2 (or .1) under Redhat Linux Fedora FC4 -03 breaks the alignment code
#

CC= gcc -g -O -DSW_SSE2 -msse2
#CC = gcc -g -DDEBUG -DSW_SSE2 -msse2

#CC=gcc -Wall -pedantic -ansi -g -O
#CC= /usr/local/parasoft/bin/insure -g -DDEBUG

# EBI uses the following with pgcc, -O3 does not work:
# CC= pgcc -O2 -pipe -mcpu=pentiumpro -march=pentiumpro -fomit-frame-pointer

# this file works for x86 LINUX

# standard options
CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="':'" -c -DMAX_WORKERS=8 -DTHR_EXIT=pthread_exit -DPROGRESS -DFASTA_HOST='"your_fasta_host_here"' -DUSE_MMAP -D_REENTRANT -DHAS_INTTYPES -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_FSEEKO -DSAMP_STATS -DPGM_DOC

# use options below for superfamily validations
#CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="'|'" -c -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit -DPROGRESS -DSUPERFAMNUM -DUSE_MMAP -D_REENTRANT -DBIG_LIB64 -D_LARGE_FILE_SOURCE -DUSE_FSEEKO -D_FILE_OFFSET_BITS=64 -DHAS_INTTYPES -DSAMP_STATS

# -I/usr/local/include/mysql -DMYSQL_DB 
#
#(for mySQL databases)  (also requires change to Makefile34.common)

LIB_M = -lm
#LIB_M = -L/usr/local/lib/mysql -lmysqlclient -lm
# for mySQL databases

HFLAGS= -o
NFLAGS= -o

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

XDIR = /seqprg/bin
#XDIR = ~/bin/LINUX

DROPNFA_O = drop_nfa.o
DROPTFA_O = drop_tfa.o
DROPGSW_O = dropgsw.o smith_waterman_sse2.o
DROPRSS_O = dropgsw.o smith_waterman_sse2.o

# renamed (fasta33)  programs
include Makefile34m.common
# conventional (fasta3) names
# include Makefile.common

