#
# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
#
# On the version of linux that I use, MININT is defined and causes a warning
# as dropnfa.c is compiled.  Unfortunately, using the Linux definition of
# MININT causes the code to break. Do not change the MININT definition
# in dropnfa.c  (wrp 3/19/1998)
#
# for DEC/Compaq Alpha/LINUX, use gcc -mieee -g to avoid buggy compilers

CC= gcc -g -O
#CC= gcc -g -DDEBUG
#CC=/opt/parasoft/bin.linux2/insure -g -DDEBUG

# this file works for x86 LINUX

# standard options
CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="':'" -c -DMAX_WORKERS=2 -DTHR_EXIT=pthread_exit -DPROGRESS -DFASTA_HOST='"your_fasta_host_here"' -DUSE_MMAP -D_REENTRANT -I/usr/local/pgsql/include -DPGSQL_DB -D_FILE_OFFSET_BITS=64 -DUSE_FSEEKO -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DHAS_INTTYPES -DSAMP_STATS -DPGM_DOC -DM10_CONS

# use options below for superfamily validations
#CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="'|'" -c -DMAX_WORKERS=2 -DTHR_EXIT=pthread_exit -DPROGRESS -DSUPERFAMNUM -DUSE_MMAP -D_REENTRANT

# -I/usr/local/include/mysql -DMYSQL_DB 
#
#(for mySQL databases)  (also requires change to Makefile34.common)

#LIB_M = -lm
#LIB_M = -L/usr/lib/mysql -lmysqlclient -lm
# for mySQL databases

HFLAGS= -o
NFLAGS= -o

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

XDIR = /seqprg/bin

DROPNFA_O = drop_nfa.o
DROPGSW_O = dropgsw.o
DROPRSS_O = dropnsw.o
DROPTFA_O = drop_tfa.o

# renamed (fasta34)  programs
include Makefile34m.common_pgsql
# conventional (fasta3) names
# include Makefile.common
